# Generated by Django 4.0.5 on 2022-10-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_category_movie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classmodel', models.CharField(blank=True, max_length=100, null=True, verbose_name='classmodel')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='classmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.classmodel', verbose_name='Category'),
        ),
    ]
