# Generated by Django 4.0.5 on 2022-10-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_classmodel_movie_classmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=100, null=True, verbose_name='Video Çeşidi')),
            ],
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='classmodel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Populer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.video', verbose_name='Video Film yada Dizi'),
        ),
    ]
