# Generated by Django 4.0.5 on 2022-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_video_alter_classmodel_classmodel_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='appMy.video', verbose_name='Video Film yada Dizi'),
        ),
    ]
