# Generated by Django 4.0.5 on 2022-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchild',
            name='slug',
            field=models.SlugField(default=1, editable=False, verbose_name='Profil İlk Adı'),
            preserve_default=False,
        ),
    ]
